#!/usr/bin/python3
#+
# Example server for chunk protocol, using asyncio.
#
# Copyright 2020 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import os
import struct
import errno
from weakref import \
    ref as weak_ref
import operator
import time
import socket
import asyncio
import common
from common import \
    TIME_UNIT, \
    chunk, \
    ID

loop = asyncio.get_event_loop()

#+
# Useful stuff
#-

def unlink_if(pathname) :
    "tries to delete pathname, ignoring any error if it doesn't exist."
    try :
        os.unlink(pathname)
    except OSError as err :
        if err.errno != errno.ENOENT :
            # Not bothering to recover from privilege failures
            raise
        #end if
    #end try
#end unlink_if

#+
# Logging
#-

class logfile :

    log = sys.stderr # where output actually goes
    flush_timeout = 0.5 # maximum delay before flushing log
    flush_pending = None # current pending-flush task, if any

    @staticmethod
    def timestamp(when = None) :
        "returns a UTC timestamp in the form yyyymmdddhhmmssZ for" \
        " the specified time, or the current time if not specified."
        if when == None :
            when = time.time()
        #end if
        items = time.gmtime(when)
        return \
                "%04d%02d%02d%02d%02d%02dZ" \
            % \
                (
                    items.tm_year,
                    items.tm_mon,
                    items.tm_mday,
                    items.tm_hour,
                    items.tm_min,
                    items.tm_sec,
                )
    #end timestamp

    @classmethod
    def queue_flush(celf) :
        "ensures that any buffered log messages will actually be" \
        " written within a reasonable time."
        if loop != None and celf.flush_pending == None :
            celf.flush_pending = loop.call_later(celf.flush_timeout, celf.flush)
        #end if
    #end queue_flush

    @classmethod
    def writeln(celf, msg) :
        "writes msg to the log as a separate line, prefixed with the current timestamp."
        celf.log.write \
          (
            celf.timestamp() + ": " + msg + "\n"
          )
        celf.queue_flush()
    #end writeln

    @classmethod
    def write(celf, msg) :
        "writes each separate line of msg to the log, prefixed with the current timestamp."
        now = celf.timestamp()
        lines = msg.split("\n")
        if len(lines) != 0 and len(lines[-1]) == 0 :
            lines = lines[:len(lines) - 1] # ignore empty line following last newline, if any
        #end if
        for line in lines :
            celf.log.write \
              (
                now + ": " + line + "\n"
              )
        #end for
        celf.queue_flush()
    #end write

    @classmethod
    def flush(celf) :
        "ensures all previously-output messages have really been written to the log."
        celf.flush_pending = None
        celf.log.flush()
    #end flush

#end logfile

#+
# Client communication
#-

io_timeout = 1 * TIME_UNIT.MINUTE
  # short value for testing

class RequestFailure(Exception) :
    "can be raised by request handlers to abort the current request" \
    " and abandon the client connection with a suitable message."

    def __init__(self, msg) :
        self.msg = msg
    #end __init__

#end RequestFailure

class ClientContext :
    "manages a currently-open client connection. This object is also" \
    " passed to request handlers, for use for returning responses."

    client_count = 0
    live_clients = set()
    shutting_down = False
    reasonable_request_size = 65535

    def __init__(self, conn, description) :
        celf = type(self)
        self.conn = conn
        celf.client_count += 1
        self.description = description
        self.reading_header = True
        self.chunk_id = None
        self.to_read = None
        self.data_read = None
        self.current_request = None # need to keep my own strong references to pending tasks
        self.to_write = None
        self.timeout_pending = None
        celf.live_clients.add(self)
        self.reset_timeout()
    #end __init__

    def close(self, reason) :
        "closes the connection, logging the specified reason message."
        if self.conn != None :
            logfile.writeln("closing client %s -- %s." % (self.description, reason))
            # need to ensure reader and writer listeners are removed before
            # closing socket, to avoid intermittent event-loop deadlocks
            loop.remove_reader(self)
            loop.remove_writer(self)
            self.clear_timeout()
            self.conn.close()
            self.conn = None
            celf = type(self)
            celf.live_clients.remove(self)
            if celf.shutting_down and len(celf.live_clients) == 0 :
                loop.stop()
            #end if
        #end if
    #end close

    def clear_timeout(self) :
        "clears the pending idle timeout."
        if self.timeout_pending != None :
            self.timeout_pending.cancel()
            self.timeout_pending = None
        #end if
    #end clear_timeout

    def reset_timeout(self) :
        "restarts the pending idle timeout."

        w_self = weak_ref(self)

        def idle_close() :
            self = w_self()
            if self != None :
                self.timeout_pending = None
                self.close("idle timeout")
            #end if
        #end idle_close

    #begin reset_timeout
        self.clear_timeout()
        self.timeout_pending = loop.call_later(io_timeout, idle_close)
    #end reset_timeout

    def fileno(self) :
        "lets this ClientContext object act as a read/write listener for" \
        " its client socket connection."
        return self.conn.fileno()
    #end fileno

    def read_more(self) :
        "read listener callback that fetches some more data from the client socket."
        if not self.shutting_down :
            if self.reading_header :
                if self.data_read == None :
                    self.data_read = b""
                    self.to_read = 8
                #end if
            #end if
            try :
                data = self.conn.recv(self.to_read)
            except OSError as err :
                logfile.writeln \
                  (
                        "error %d trying to read from %s."
                    %
                        (err.errno, self.description)
                  )
                data = None
            #end try
            if data != None :
                if len(data) != 0 :
                    self.reset_timeout()
                    self.data_read += data
                    self.to_read -= len(data)
                    if self.to_read == 0 :
                        if self.reading_header :
                            self.chunk_id, self.to_read = chunk.extract_header(self.data_read)
                            if self.to_read > self.reasonable_request_size :
                                self.close("request of %d bytes is too large" % self.to_read)
                            else :
                                self.data_read = b""
                                self.reading_header = False
                                if self.to_read == 0 :
                                    loop.remove_reader(self)
                                    self.process_request()
                                #end if
                            #end if
                        else :
                            loop.remove_reader(self)
                            self.process_request()
                        #end if
                    #end if
                else :
                    self.close("read EOF")
                #end if
            else :
                self.close("read error")
            #end if
        else :
            self.close("server shutting down")
        #end if
    #end read_more

    def write_more(self) :
        "write listener callback that sends some more data to the client socket."
        try :
            written = self.conn.send(self.to_write)
        except OSError as err :
            logfile.writeln \
              (
                    "error %d trying to write to %s."
                %
                    (err.errno, self.description)
              )
            written = None
        #end try
        if written != None :
            self.reset_timeout()
            self.to_write = self.to_write[written:]
            if len(self.to_write) == 0 :
                self.to_write = None
                loop.remove_writer(self)
                if not self.shutting_down :
                    # ready for next request
                    self.reading_header = True
                    self.data_read = None
                    loop.add_reader(self, self.read_more)
                else :
                    self.close("server shutting down")
                #end if
            #end if
        else :
            self.close("write error")
        #end if
    #end write_more

    def process_request(self) :
        "processes a complete received request chunk."
        self.clear_timeout() # no time limit on servicing request
        logfile.writeln("process request %s" % repr(self.chunk_id))
        func = server_functions.get(self.chunk_id)
        if func != None :
            if func["parse"] :
                args = dict(chunk.extract_iter(self.data_read))
            else :
                args = self.data_read
            #end if
            try :
                result = func["action"](self, args)
            except RequestFailure as bad :
                self.close \
                  (
                        "validation failure for request %s: %s"
                    %
                        (repr(self.chunk_id), bad.msg)
                  )
                result = None
            #end try
            if asyncio.iscoroutine(result) :
                assert self.current_request == None
                w_self = weak_ref(self)

                async def await_request_done(request_task) :
                    try :
                        result = await request_task
                    except RequestFailure as bad :
                        self = w_self()
                        if self != None :
                            self.close \
                              (
                                    "validation failure for async request %s: %s"
                                %
                                    (repr(self.chunk_id), bad.msg)
                              )
                        #end if
                    except Exception as fail :
                        # good to try to report failures due to bugs, otherwise
                        # it seems I don’t see them
                        logfile.writeln("request handler error: %s" % repr(fail))
                    #end try
                    self = w_self()
                    if self != None :
                        self.current_request = None
                    #end if
                #end await_request_done

                self.current_request = loop.create_task(await_request_done(result))
            #end if
        else :
            self.close("bad request %s" % repr(self.chunk_id))
        #end if
    #end process_request

    def return_response(self, id, contents) :
        "queues the response chunk for sending back to the client. Or id can be" \
        " None to indicate that the connection should be abandoned."
        logfile.writeln("return response (%s, %s)" % (repr(id), repr(contents)))
        assert self.to_write == None
        if id != None :
            self.to_write = chunk.make(id, contents)
            self.reset_timeout()
            loop.add_writer(self, self.write_more)
        else :
            self.close("aborting request %s" % repr(self.chunk_id))
        #end if
    #end return_response

#end ClientContext

#+
# Request handling
#-

def require_all(keys, args) :
    "raises a RequestFailure if not all the specified keys are in args."
    missing = set(k for k in keys if k not in args)
    if len(missing) != 0 :
        raise RequestFailure \
          (
            "missing required arg keywords: %s" % ", ".join(repr(k) for k in sorted(missing))
          )
    #end if
#end require_all

def handle_noop_request(client, contents) :
    client.return_response(ID.reply_noop, b"")
#end handle_noop_request

def handle_echo_request(client, contents) :
    client.return_response(ID.reply_echo, contents)
#end handle_echo_request

def handle_shutdown_request(client, contents) :
    logfile.writeln("shutdown request received from client %s." % client.description)
    ClientContext.shutting_down = True
    client.return_response(ID.reply_noop, b"")
#end handle_shutdown_request

async def handle_delay_request(client, contents) :
    require_all([ID.interval], contents)
    try :
        interval = float(contents[ID.interval].decode())
    except (ValueError, UnicodeDecodeError) :
        raise RequestFailure("invalid delay interval")
    #end try
    logfile.writeln("delay for %.3f seconds" % interval)
    await asyncio.sleep(interval)
    client.return_response(ID.reply_noop, b"")
#end def handle_delay_request

def handle_compute_request(client, contents) :

    valid_operators = \
        {
            "+" : {"op" : operator.add, "vari" : True, "ident" : 0},
            "-" : {"op" : operator.sub, "vari" : False},
            "*" : {"op" : operator.mul, "vari" : True, "ident" : 1},
            "/" : {"op" : operator.truediv, "vari" : False},
            "%" : {"op" : operator.mod, "vari" : False},
            "**" : {"op" : operator.pow, "vari" : False},
        }

#begin handle_compute_request
    oper = None
    operands = []
    result = {}
    for chunkid, subchunk in chunk.extract_iter(contents) :
        if chunkid == ID.operator :
            if oper != None :
                raise RequestFailure("more than one operator specified in compute request")
            #end if
            try :
                oper = subchunk.decode()
            except UnicodeDecodeError :
                raise RequestFailure("invalid operator %s in compute request" % repr(subchunk))
            #end if
        elif chunkid == ID.operand :
            try :
                operand = complex(subchunk.decode())
            except (ValueError, UnicodeDecodeError) :
                raise RequestFailure("invalid operand %s in compute request" % repr(subchunk))
            else :
                if operand.imag == 0 :
                    operand = operand.real
                #end if
            #end if
            operands.append(operand)
        else :
            raise RequestFailure("invalid subchunk ID %s in compute request" % repr(chunkid))
        #end if
    #end for
    if oper == None :
        raise RequestFailure("missing operator in compute request")
    #end if
    if oper not in valid_operators :
        raise RequestFailure("unrecognized operator %s in compute request" % repr(subchunk))
    #end if
    op = valid_operators[oper]
    if not op["vari"] and len(operands) != 2 :
        raise RequestFailure("invalid number of operands in compute request")
    #end if
    if op["vari"] :
        value = op["ident"]
        for opnd in operands :
            value = op["op"](value, opnd)
        #end for
        success = True
    else :
        try :
            value = op["op"](*operands)
        except (ZeroDivisionError, TypeError) :
            success = False
        else :
            success = True
        #end try
    #end if
    if success :
        if value.imag == 0 :
            value = value.real
        #end if
        result[ID.value] = str(value).encode()
    #end if
    result[ID.status] = ("0", "1")[success]
    client.return_response(ID.reply_answer, result)
#end handle_compute_request

server_functions = \
    { # Table of recognized request codes and corresponding handlers.
      # Key is request code, value is dict with entries:
      #     "action" : request handler
      #     "parse" : whether to automatically parse the top-level
      #         request chunk into a dictionary of subchunks.
        ID.request_noop :
            {
                "action" : handle_noop_request,
                "parse" : False,
            },
        ID.request_echo :
            {
                "action" : handle_echo_request,
                "parse" : False,
            },
        ID.request_shutdown :
            {
                "action" : handle_shutdown_request,
                "parse" : True,
            },
        ID.request_delay :
            {
                "action" : handle_delay_request,
                "parse" : True,
            },
        ID.request_compute :
            {
                "action" : handle_compute_request,
                "parse" : False,
            },
    }

#+
# Mainline
#-

def accept_connection(server_listen) :
    "read listener on the socket for accepting client connections."
    try :
        conn, peername = server_listen.accept()
    except OSError as err :
        logfile.writeln \
          (
            "server_loop: error %d trying to accept connection." % err.errno
          )
        conn = None
    #end try
    if conn != None :
        # peername always empty for unix-family socket connection.
        # even conn.getpeername() returns empty string.
        u_cred = "=iII"
          # as per sys/socket.h: struct { pid_t pid; uid_t uid; gid_t gid; }
          # -- all 32 bits on Linux AMD64
        peercred = conn.getsockopt(socket.SOL_SOCKET, socket.SO_PEERCRED, struct.calcsize(u_cred))
        pid, uid, gid = struct.unpack(u_cred, peercred)
        description = "pid %d, uid %d, gid %d" % (pid, uid, gid)
        if not ClientContext.shutting_down :
            logfile.writeln \
              (
                "connection from %s" % description
              )
            client = ClientContext(conn, description)
            loop.add_reader(client, client.read_more)
        else :
            logfile.writeln \
              (
                "reject connection from %s" % description
              )
            conn.close()
        #end if
    #end if
#end accept_connection

def start_server() :
    server_listen = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM | socket.SOCK_NONBLOCK)
    unlink_if(common.socket_name)
    server_listen.bind(common.socket_name)
    os.chmod(common.socket_name, 0o777)
    server_listen.listen(socket.SOMAXCONN)
    loop.add_reader(server_listen, accept_connection, server_listen)
#end start_server

logfile.writeln("example server starting up")
start_server()
loop.run_forever()
unlink_if(common.socket_name)
loop = None # stop calling logfile.queue_flush()
logfile.writeln("example server shutting down")
logfile.flush()
